---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Hands_in_Pettakere_Cave_DYK_crop/Hands_in_Pettakere_Cave_DYK_crop.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/199651/master/file/figures/Hands_in_Pettakere_Cave_DYK_crop/Hands_in_Pettakere_Cave_DYK_crop.png"
    folder_url: "/users/87737/articles/199651/master/folder/figures/Hands_in_Pettakere_Cave_DYK_crop"
